### ISSUE TITLE
[FALSE-POSITIVE?] jsfiddle.net

### ISSUE THREAD

**Issue by sbine** [Ultimate-Hosts-Blacklist/whitelist#152]
**Domains or links**
- jsfiddle.net
- fiddle.jshell.net

**More Information**
How did you discover your web site or domain was listed here?
1. It's not my website; I'm a developer who often uses JS Fiddle to view/run other people's code snippets

**Have you requested removal from other sources?**
No

**Additional context**
JS Fiddle is a generic code hosting tool/playground used often by developers to demonstrate how little bits of code work. Since all the code is uploaded by users, the site may have been flagged as containing tracking snippets or something, but it's not actually used for tracking (to my knowledge).

**Comment by funilrys** [comment]
As per [our lookup database](https://hosts.ubuntu101.co.za/app/contents) it's part of the [Phishing.Database](https://github.com/mitchellkrogza/Phishing.Database) (cc @mitchellkrogza).

I chose to whitelist this because we (developers at least) know how important JS Fiddle can be nowadays.

Thanks for reporting @sbine and sorry for the disturbance. 
This will be whitelisted from the infrastructure from now on and soon as possible from [our central repository](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist) and [our DNS server](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/590)  (more info about the update schedules [here](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#when-is-the-list-updated)).

Have a nice day/night.
Stay safe and healthy.
Nissar
